num1=int(input("Enter the first number:"))
num2=int(input("Enter the second number :"))
sum=num1+num2
difference=num1-num2
product=num1*num2
division=num1/num2
modulus=num1%num2
exponent=num1**num2
print(f"Sum:{num1}+{num2}={sum}")
print(f"Difference:{num1}-{num2}={difference}")
print(f"Product:{num1}*{num2}={product}")
print(f"Division:{num1}/{num2}={division}")
print(f"Modulus:{num1}%{num2}={modulus}")
print(f"Exponent:{num1}**{num2}={exponent}")
